### ISSUE TITLE
Push a release to cargo

### ISSUE THREAD

**Issue by jgarzik** [cholcombe973/gdbm#6]
The latest version fetched from `cargo` is 0.1.1.

Request to push the current code as a new release to cargo.

**Comment by cholcombe973** [comment]
What linux operating system are you trying to build this on?

**Comment by jgarzik** [comment]
This is observed on macOS Big Sur 11.6.7, but it is not an OS-specific issue.  The most recent version of this package is from **2018**, version 0.1.1:
```
$ cargo show gdbm
---
id: gdbm
name: gdbm
description: Safe wrapper for gdbm-sys bindings
documentation: None
homepage: https://github.com/cholcombe973/gdbm
repository: None
max_version: 0.1.1
downloads: 1135
license: None
created: 2017-05-05T23:35:27.216368+00:00
updated: 2018-07-31T01:40:47.278325+00:00
```

The changes in git from July 2018 until now are not available via cargo release.  This issue is requesting that a new version be released to cargo.

**Comment by cholcombe973** [comment]
Yeah I got going on this and then lost track of it. I'll try to push a release in the next day.
